services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_auth
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: