services:
#  api:
#    container_name: python_api
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 8000:8000

  postgres:
    image: postgres:14-alpine
    container_name: postgres_site
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: